defaults: &defaults
  admin_feature1: true
  admin_feature2: false
  admin_feature3: false

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults

