defaults: &defaults
  public_feature1: true
  public_feature2: false
  public_feature3: false

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults