language: ruby
services:
  - redis-server
addons:
  code_climate:
    repo_token: 535ff40cf55554362b2f48b85e913a7362f0cf3e51638455dab456006258c5a0
rvm:
  - 2.2.1
  - 2.1.5
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - ree
  - jruby-18mode
  - jruby-19mode
  - rbx-2.5.2
gemfile:
  - Gemfile
  - ruby187.Gemfile
matrix:
  exclude:
    - rvm: 2.2.1
      gemfile: ruby187.Gemfile
    - rvm: 2.1.5
      gemfile: ruby187.Gemfile
    - rvm: 2.0.0
      gemfile: ruby187.Gemfile
    - rvm: 1.9.3
      gemfile: ruby187.Gemfile
    - rvm: 1.8.7
      gemfile: Gemfile
    - rvm: ree
      gemfile: Gemfile
    - rvm: jruby-18mode
      gemfile: Gemfile
    - rvm: jruby-19mode
      gemfile: Gemfile
    - rvm: rbx-2.5.2
      gemfile: ruby187.Gemfile
