language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - ree
  - jruby-18mode
  - jruby-19mode
  - rbx-2.1.1
gemfile:
  - Gemfile
  - ruby187.Gemfile
matrix:
  include:
    - rvm: 2.0.0
      gemfile: Gemfile
    - rvm: 1.9.3
      gemfile: Gemfile
    - rvm: 1.8.7
      gemfile: ruby187.Gemfile
    - rvm: ree
      gemfile: ruby187.Gemfile
    - rvm: jruby-18mode
      gemfile: Gemfile
    - rvm: jruby-19mode
      gemfile: Gemfile
    - rvm: rbx-2.1.1
      gemfile: ruby187.Gemfile