# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: abstract_feature_branch 1.6.0 ruby lib

Gem::Specification.new do |s|
  s.name = "abstract_feature_branch".freeze
  s.version = "1.6.0".freeze

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Andy Maleh".freeze]
  s.date = "2024-01-22"
  s.description = "abstract_feature_branch is a Ruby gem that provides a unique variation on the Branch by Abstraction Pattern by Paul Hammant and the Feature Toggles Pattern by Martin Fowler to enhance team productivity and improve software fault tolerance.\n\nIt provides the ability to wrap blocks of code with an abstract feature branch name, and then specify in a configuration file which features to be switched on or off.\n\nThe goal is to build out upcoming features in the same source code repository branch (i.e. Continuous Integration and Trunk-Based Development), regardless of whether all are completed by the next release date or not, thus increasing team productivity by preventing integration delays. Developers then disable in-progress features until they are ready to be switched on in production, yet enable them locally and in staging environments for in-progress testing.\n\nThis gives developers the added benefit of being able to switch a feature off after release should big problems arise for a high risk feature.\n\nabstract_feature_branch additionally supports Domain Driven Design's pattern of Bounded Contexts by allowing developers to configure context-specific feature files if needed.\n\nabstract_feature_branch is one of the simplest and most minimalistic \"Feature Flags\" Ruby gems out there as it enables you to get started very quickly by simply leveraging YAML files without having to set up a data store if you do not need it (albeit, you also have the option to use Redis as a very fast in-memory data store).\n".freeze
  s.extra_rdoc_files = [
    "CHANGELOG.md",
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "CHANGELOG.md",
    "LICENSE.txt",
    "README.md",
    "VERSION",
    "abstract_feature_branch.gemspec",
    "lib/abstract_feature_branch.rb",
    "lib/abstract_feature_branch/configuration.rb",
    "lib/abstract_feature_branch/file_beautifier.rb",
    "lib/abstract_feature_branch/memoizable.rb",
    "lib/abstract_feature_branch/redis/connection_pool_to_redis_adapter.rb",
    "lib/ext/feature_branch.rb",
    "lib/generators/abstract_feature_branch/context_generator.rb",
    "lib/generators/abstract_feature_branch/install_generator.rb",
    "lib/generators/templates/config/features.example.yml",
    "lib/generators/templates/config/features.local.yml",
    "lib/generators/templates/config/features.yml",
    "lib/generators/templates/config/initializers/abstract_feature_branch.rb",
    "lib/generators/templates/lib/tasks/abstract_feature_branch.rake"
  ]
  s.homepage = "http://github.com/AndyObtiva/abstract_feature_branch".freeze
  s.licenses = ["MIT".freeze]
  s.post_install_message = "\nRails-only post-install instructions:\n\n1) Run the following command to generate the Rails initializer and basic feature files:\n\nrails g abstract_feature_branch:install\n\n2) Optionally, you may run this command to generate feature files per context:\n\nrails g abstract_feature_branch:context context_path\n   \n3) Optionally, install Redis server with [Homebrew](https://brew.sh/) by running:\n\nbrew install redis\n\n4) Optionally, install redis client gem (required with Redis server) by adding the following line to Gemfile above abstract_feature_branch:\n\ngem 'redis', '~> 5.0.5'\n\nAfterwards, run:\n\nbundle\n\n5) Optionally, customize configuration in config/initializers/abstract_feature_branch.rb\n\n(can be useful for changing location of feature files in Rails application,\nconfiguring Redis with a Redis or ConnectionPool instance to use for overrides and scoped feature enablement (e.g. per-user),\nand/or troubleshooting specific Rails environment feature configurations)\n\n".freeze
  s.rubygems_version = "3.5.3".freeze
  s.summary = "abstract_feature_branch is a Ruby gem that provides a variation on the Branch by Abstraction Pattern by Paul Hammant and the Feature Toggles Pattern by Martin Fowler (aka Feature Flags) to enable Continuous Integration and Trunk-Based Development.".freeze

  s.specification_version = 4

  s.add_runtime_dependency(%q<deep_merge>.freeze, [">= 1.0.0".freeze, "< 2.0.0".freeze])
  s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.3.9".freeze])
  s.add_development_dependency(%q<bundler>.freeze, [">= 2.1.4".freeze])
  s.add_development_dependency(%q<rspec>.freeze, ["~> 3.12.0".freeze])
  s.add_development_dependency(%q<rdoc>.freeze, ["= 5.1.0".freeze])
  s.add_development_dependency(%q<psych>.freeze, ["= 3.3.4".freeze])
  s.add_development_dependency(%q<rake-tui>.freeze, ["~> 0.2".freeze])
end

