defaults: &defaults
  FEATURE1: true
  Feature2: true
  feature3: false
  feature4: true
  feature4a: true

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults
#  feature2: false

production:
  <<: *defaults
#  feature1: false
#  feature2: false
