defaults: &defaults
  FEATURE1: true
  Feature2: true
  feature3: true

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults
  FEATURE1: true
  Feature2: false
  feature3: true

production:
  <<: *defaults

